platform :ios, '11.0'

require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'PodcastMarketingAutomation' do
  config = use_native_modules!

  use_react_native!(:path => config[:reactNativePath])

  # Pods for PodcastMarketingAutomation
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  target 'PodcastMarketingAutomationTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end

# HUMAN TASKS:
# TODO: Verify the iOS deployment target (currently set to '11.0') is appropriate for the project requirements
# TODO: Confirm that all necessary iOS-specific dependencies are included in the Podfile
# TODO: Ensure the correct target name 'PodcastMarketingAutomation' is used throughout the project