apiVersion: v1
kind: Secret
metadata:
  name: podcast-automation-secrets
  namespace: default
type: Opaque
data:
  database-url: {{ BASE64_ENCODED_DATABASE_URL }}
  aws-access-key-id: {{ BASE64_ENCODED_AWS_ACCESS_KEY_ID }}
  aws-secret-access-key: {{ BASE64_ENCODED_AWS_SECRET_ACCESS_KEY }}
  jwt-secret: {{ BASE64_ENCODED_JWT_SECRET }}
  social-media-api-keys: {{ BASE64_ENCODED_SOCIAL_MEDIA_API_KEYS }}

# Human Tasks:
# - Replace {{ BASE64_ENCODED_DATABASE_URL }} with the base64 encoded database connection string
# - Replace {{ BASE64_ENCODED_AWS_ACCESS_KEY_ID }} with the base64 encoded AWS access key ID
# - Replace {{ BASE64_ENCODED_AWS_SECRET_ACCESS_KEY }} with the base64 encoded AWS secret access key
# - Replace {{ BASE64_ENCODED_JWT_SECRET }} with the base64 encoded JWT secret for authentication
# - Replace {{ BASE64_ENCODED_SOCIAL_MEDIA_API_KEYS }} with the base64 encoded JSON object containing API keys for various social media platforms
# - Ensure that the Secret is created in the same namespace as the Deployment that uses it
# - Implement proper secret management and rotation policies for production use